export const text = {
  ar: {
    nav: ["المنتجات", "عالم Claréa", "عن Claréa", "الأسئلة الشائعة"],
    intro: "روتين العناية يبدأ هنا.",
    description:
      "اكتشفي منتجات العناية بالبشرة والشعر وتعرّفي على مكوناتها وطريقة استخدامها قبل الاختيار.",
    edit: "THE CARE EDIT / 01",
    collection: "تسوّقي كل المنتجات",
    all: "كل المنتجات",
    skin: "العناية بالبشرة",
    hair: "العناية بالشعر",
    supplements: "المكملات الغذائية",
    oral: "العناية بالفم",
    body: "العناية بالجسم",
    search: "ابحثي عن منتج أو ماركة",
    available: "متاح الآن",
    unavailable: "غير متاح حاليًا",
    stock: "المتاح فقط",
    sort: "ترتيب المنتجات",
    featured: "اختيارات Claréa",
    bestSelling: "الأكثر مبيعاً 🔥",
    priceLowHigh: "السعر: من الأقل للأعلى ⬆️",
    priceHighLow: "السعر: من الأعلى للأقل ⬇️",
    az: "الاسم: أ – ي",
    results: "منتجات",
    details: "تفاصيل المنتج",
    empty: "لم نجد منتجات بهذه المواصفات",
    reset: "عرض كل المنتجات",
    close: "إغلاق",
    previous: "الصورة السابقة",
    next: "الصورة التالية",
    order: "استفسري واطلبي عبر واتساب",
    ask: "استفسري عن التوفر",
    note: "المنتجات غير المتاحة معروضة للاستكشاف، ولا يمكن طلبها حاليًا.",
    journal: "عالم Claréa",
    journalCopy: "مجموعات لروتينك اليومي.",
    studio: "التنظيف في خطوتين.",
    studioCopy: "اكتشفي مجموعة التنظيف في خطوتين.",
    about: "تعرّفي على Claréa.",
    aboutCopy:
      "في Claréa، نجمع لكِ اختيارات من العناية بالبشرة والشعر مع تفاصيل عن المكونات والاستخدام. تصفّحي المنتجات، وتواصلي معنا على واتساب للاستفسار أو لتأكيد تفاصيل طلبك.",
    values: ["عناية بالبشرة والشعر", "معلومات واضحة", "تواصل مباشر"],
    faq: "الأسئلة الشائعة",
    faqs: [
      [
        "هل كل المنتجات المعروضة متاحة؟",
        "حالة التوفر موضحة على كل منتج. استخدمي خيار «المتاح فقط» لتصفّح المنتجات المتاحة، وأكدي التوفر معنا عند الطلب.",
      ],
      [
        "كيف أطلب؟",
        "افتحي تفاصيل المنتج واضغطي زر واتساب. نؤكد معكِ السعر النهائي والتوفر وتكلفة الشحن قبل إتمام الطلب.",
      ],
      [
        "هل يمكنكم مساعدتي في الاختيار؟",
        "أرسلي لنا اسم المنتج وما تبحثين عنه في روتينك. نساعدك على فهم المكونات وطريقة الاستخدام؛ وللحالات الجلدية، استشيري طبيب جلدية.",
      ],
      [
        "كيف أتابع المنتجات الجديدة؟",
        "تابعي قسم New to Claréa (الجديد في Claréa) في الصفحة الرئيسية؛ ده المكان اللي بنعرض فيه المنتجات الجديدة. افتحي أي منتج لمعرفة تفاصيله وحالة توفره.",
      ],
    ],
    footer: "معلومات العناية لا تغني عن استشارة مختص عند وجود حالة جلدية.",
  },
  en: {
    nav: ["Shop all", "The Claréa edit", "About Claréa", "FAQs"],
    intro: "Your daily care starts here.",
    description:
      "Discover beauty and care and explore product ingredients and how to use them before you choose.",
    edit: "THE CARE EDIT / 01",
    collection: "Shop all products",
    all: "All products",
    skin: "Skincare",
    hair: "Haircare",
    supplements: "Supplements",
    oral: "Oral care",
    body: "Body Care",
    search: "Search for a product or brand",
    available: "Available now",
    unavailable: "Currently unavailable",
    stock: "Available only",
    sort: "Sort products",
    featured: "Claréa selections",
    bestSelling: "Best Selling 🔥",
    priceLowHigh: "Price: Low to High ⬆️",
    priceHighLow: "Price: High to Low ⬇️",
    az: "Name: A–Z",
    results: "products",
    details: "View product",
    empty: "No products match your selection",
    reset: "View all products",
    close: "Close",
    previous: "Previous image",
    next: "Next image",
    order: "Enquire & order on WhatsApp",
    ask: "Ask about availability",
    note: "Unavailable products are shown for discovery and cannot currently be ordered.",
    journal: "The Claréa edit",
    journalCopy: "Discover our skincare sets.",
    studio: "Your two-step cleanse.",
    studioCopy: "Meet the two-step cleansing duo.",
    about: "Get to know Claréa.",
    aboutCopy:
      "At Claréa, discover a selection of beauty and care with clear ingredient and usage information. Browse the collection and contact us on WhatsApp for product questions or to confirm your order details.",
    values: ["beauty and care", "Clear product details", "Direct support"],
    faq: "Frequently asked questions",
    faqs: [
      [
        "Are all listed products available?",
        "Each product shows its availability. Use the Available only filter to browse available products, and confirm stock with us when ordering.",
      ],
      [
        "How do I order?",
        "Open the product details and select the WhatsApp button. We will confirm the final price, availability and shipping cost before you place your order.",
      ],
      [
        "Can you help me choose?",
        "Send us the product name and what you are looking for in your routine. We can explain ingredients and usage. For skin conditions, consult a dermatologist.",
      ],
      [
        "How can I follow new arrivals?",
        "Visit New to Claréa on the homepage to discover newly added products. Open any product to see its details and availability.",
      ],
    ],
    footer: "Care information does not replace professional advice for skin conditions.",
  },
};
