export const rewardsText = {
  ar: {
    tab: "لفّي واكسبي",
    title: "هدية صغيرة من Claréa 🎁",
    intro: "دوري العجلة لاكتشاف هدية أو خصم لطلبك. تُؤكد النتيجة مع فريقنا وفق شروط العرض.",
    spin: "جرّبي حظك",
    spinning: "جاري تدوير العجلة…",
    congrats: "تهانينا",
    result: "نتيجتك:",
    reference: "رقم مرجع الهدية",
    claim: "تواصلي لتأكيد الهدية",
    copy: "نسخ الرقم",
    copied: "تم النسخ",
    copyError: "يمكنك تحديد الرقم ونسخه يدويًا",
    close: "إغلاق",
    whatsapp: "تواصلي معنا على واتساب",
    rules: "شروط الهدايا",
    storage: "المتصفح لا يسمح بحفظ المشاركة؛ النتيجة محفوظة لهذه الزيارة فقط.",
    saved: "هذه نتيجة مشاركتك المحفوظة في العرض الحالي.",
    search: "البحث عن المنتجات",
    gifts: "هدايا Claréa",
    phoneLabel: "أدخلي رقمك لتدوير العجلة",
    phonePlaceholder: "رقم الهاتف مع رمز الدولة",
    phoneRequired: "الرجاء إدخال رقم هاتف صحيح",
  },
  en: {
    tab: "Spin to win",
    title: "A little gift from Claréa 🎁",
    intro: "Spin for a gift or discount on your order. Results are subject to confirmation by our team and the offer terms.",
    spin: "Try your luck",
    spinning: "Spinning…",
    congrats: "Congratulations",
    result: "Your result:",
    reference: "Gift reference",
    claim: "Confirm your gift on WhatsApp",
    copy: "Copy reference",
    copied: "Copied",
    copyError: "Select the reference to copy it manually",
    close: "Close",
    whatsapp: "Chat with us on WhatsApp",
    rules: "Gift terms",
    storage: "Your browser blocks storage; this result is saved for this visit only.",
    saved: "Your saved result for this offer.",
    search: "Search products",
    gifts: "Claréa gifts",
    phoneLabel: "Enter your number to spin the wheel",
    phonePlaceholder: "Phone number with country code",
    phoneRequired: "Please enter a valid phone number",
  },
};

